# -*- coding: utf-8 -*-
"""automatic_speech.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuFLG_iDc4a72qAY6IkBJEYAndoKVEfO
"""



#pip install automatic-speech-recognition
from IPython.display import Audio

import automatic_speech_recognition as asr
import librosa
data,_=librosa.load("OAF_search_angry.wav",sr=16000)    #input file to include
#file = 'OAF_search_angry.wav'  # sample rate 16 kHz, and 16 bit depth
#sample = asr.utils.read_audio(file)
pipeline = asr.load('deepspeech2', lang='en')
pipeline.model.summary()     # TensorFlow model
sentences = pipeline.predict([data])

print(sentences)


##Audio("OAF_search_angry.wav")   #(to play the audio)

