# -*- coding: utf-8 -*-
"""nemo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cMNG72lwXsNtCdAjNiAdzokaSVLpYMAR
"""


import nemo.collections.asr as nemo_asr
asr_model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained("nvidia/stt_en_conformer_ctc_large")

print(asr_model.transcribe(['OAF_search_angry.wav']))

print(asr_model.transcribe(['h_orig.wav']))

print(asr_model.transcribe(['male.wav']))











