# -*- coding: utf-8 -*-
"""speech_brain_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QMhFdzvIWG2gIYvgOFpCU3fBKoWsNEad
"""

#pip install speechbrain transformers
from IPython.display import Audio

from speechbrain.pretrained import EncoderDecoderASR

asr_model = EncoderDecoderASR.from_hparams(source="speechbrain/asr-wav2vec2-commonvoice-en", savedir="pretrained_models/asr-wav2vec2-commonvoice-en")

print(asr_model.transcribe_file("h_noise.wav"))  #input files to include

print(asr_model.transcribe_file("male.wav"))



##Audio("male.wav")  #to play the audio sound


